// Generated by ts-to-zod
import { z } from "zod";
import { exportTypesSchema } from "./ExportTypes";

export const overviewFieldsSchema = z.object({
  name: z.string().nullable(),
  tags: z.string().nullable(),
  export_type: exportTypesSchema.nullable(),
  playtime: z.number().nullable(),
});
