// Generated by ts-to-zod
import { z } from "zod";
import { instanceFieldsSchema } from "../InstanceFields";
import { baseMessageSchema } from "lib/msgBindings";

export const optionUpdateMessageSchema = z.object({
    base: baseMessageSchema,
    option: instanceFieldsSchema
});
