// Generated by ts-to-zod
import { z } from "zod";

export const baseMessageSchema = z.object({
  message_id: z.string(),
  operation_id: z.string().nullish(),
  request_id: z.string().nullish(),
  timestamp: z.string(),
  correlation_id: z.string().nullish(),
});
