// Generated by ts-to-zod
import { z } from "zod";
import { operationStartSchema } from "./OperationStart";
import { operationUpdateSchema } from "./OperationUpdate";
import { operationFinishSchema } from "./OperationFinish";


export const operationEventSchema = z.union([
  z.object({
    start: operationStartSchema,
  }),
  z.object({
    update: operationUpdateSchema,
  }),
  z.object({
    finish: operationFinishSchema,
  }),
]);
