// Generated by ts-to-zod
import { z } from "zod";
import { operationStageSchema } from "./OperationStage";


export const operationStartSchema = z.object({
  stages: z.array(operationStageSchema),
});
