// Generated by ts-to-zod
import { z } from "zod";

export const operationStageSchema = z.union([
  z.literal("fetch_manifest"),
  z.literal("download_libs"),
  z.literal("download_assets"),
  z.literal("verify_files"),
  z.literal("create_structure"),
  z.literal("scan_instances"),
]);
