// Generated by ts-to-zod
import { z } from "zod";
import { baseMessageSchema } from "./BaseMessage";
import { operationEventSchema } from "./OperationEvent";


export const operationMessageSchema = z.object({
    data: operationEventSchema,
}).merge(baseMessageSchema);
