// Generated by ts-to-zod
import { z } from "zod";
import { scanInfoSchema } from "./ScanInfo";
import { scanIntegritySchema } from "./ScanIntegrity";


export const scanDataSchema = z.object({
  integrity: scanIntegritySchema,
  info: scanInfoSchema.nullish(),
});
