// Generated by ts-to-zod
import { z } from "zod";
import { stageErrorSchema } from "./StageError";
import { operationStageSchema } from "./OperationStage";
import { stageStatusSchema } from "./StageStatus";


export const stageResultSchema = z.object({
  status: stageStatusSchema,
  stage: operationStageSchema,
  duration_secs: z.number(),
  error: stageErrorSchema.nullish(),
});
