// Generated by ts-to-zod
import { z } from "zod";
import { operationMessageSchema } from "./OperationMessage";
import { scanMessageSchema } from "./ScanMessage";


export const wsMessageSchema = z.discriminatedUnion("type", [
  z.object({
    type: z.literal("operation"),
    payload: operationMessageSchema,
  }),
  z.object({
    type: z.literal("scan"),
    payload: scanMessageSchema,
  }),
]);
