// Generated by ts-to-zod
import { z } from "zod";
import { scanMessageSchema } from "./ScanMessage";
import { optionUpdateMessageSchema } from "./instance/options/OptionUpdateMessage";
import { operationMessageSchema } from "./OperationMessage";


export const indexMessageSchema = z.discriminatedUnion("type", [
  z.object({
    type: z.literal("operation"),
    payload: operationMessageSchema,
  }),
  z.object({
    type: z.literal("scan"),
    payload: scanMessageSchema,
  }),
  z.object({
      type: z.literal("option"),
      payload: optionUpdateMessageSchema
  })
]);
