// Generated by ts-to-zod
import { z } from "zod";

export const scanIntegritySchema = z.object({
  manifest_path: z.string(),
  manifest_exist: z.boolean(),
  instance_path: z.string(),
  instance_exist: z.boolean(),
});
