// Generated by ts-to-zod
import { z } from "zod";
import { baseMessageSchema } from "./BaseMessage";
import { scanDataSchema } from "./ScanData";

export const scanMessageSchema = z.object({
  base: baseMessageSchema,
  data: scanDataSchema,
});
