// Generated by ts-to-zod
import { z } from "zod";

export const stageStatusSchema = z.union([
  z.literal("started"),
  z.literal("in_progress"),
  z.literal("completed"),
  z.literal("failed"),
]);
