// Generated by ts-to-zod
import { z } from "zod";
import { dirStatusSchema } from "./DirStatus";
import { fileStatusSchema } from "./FileStatus";


export const targetStatusSchema = z.union([
  z.object({
    file: fileStatusSchema,
  }),
  z.object({
    dir: dirStatusSchema,
  }),
]);
