// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { z } from "zod";
import { operationStageSchema } from "./OperationStage";
import { taskStatusSchema } from "./TaskStatus";
import { taskProgressSchema } from "./TaskProgress";

export const taskSchema = z.object({
    data: z.object({
        name: z.string(),
        status: taskStatusSchema,
        stage: operationStageSchema.nullish(),
        progress: taskProgressSchema,
        message: z.string().nullish()
    }),
    id: z.number()
})
