// Generated by ts-to-zod
import { z } from "zod";
import { overviewFieldsSchema } from "./options/overview/OverviewFields";
import { settingsFieldsSchema } from "./options/settings/SettingsFields";

export const instanceFieldsSchema = z.union([
  z.object({
    Overview: overviewFieldsSchema,
  }),
  z.object({
    Settings: settingsFieldsSchema,
  }),
]);
